language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381808-1_KrasilnikovAV_Lab
  - make -j
  - ls
  - ./Test
notifications:
  email: false
